### ISSUE TITLE
Unterschiedliche Zeilenumbrüche für Kommentare (;) und Einheiten

### ISSUE THREAD

**Issue by Xolgrim** [gulrak/pbemtools#1]
Ich habe den Zeilenumbruch auf 1000 gestellt, damit ich in den Routen meiner Schiffe nicht immer einen Umbruch drin habe. Leider wirkt sich das auch auf die Zeilenumbrüche der Kommentare aus, was besonders bei der Zeile " ; Materialpool:" in Regionen in denen man viel und unterschiedliches Zeig liegen hat sehr unübersichtlich bei der Darstellung ist. Wenn das nicht zu aufwändig ist würde ich mir unterschiedliche Optionen für den Zeilenumbruch der Einheiten und den Zeilenumbruch von Kommentaren (mit ;) wünschen.

**Comment by gulrak** [comment]
Released mit v1.7.3
