### ISSUE TITLE
Werte nahe an 0xffffffff

### ISSUE THREAD

**Issue by hochl** [gulrak/pbemtools#12]
Hallo,

Hier scheint was nicht zu passen, es schaut wie ein negativer Wert aus der als uint32_t interpretiert wird.

 10: 26560 ;  . .  |Pl. frei: 4294967283 -1|                    |                     |
 11: 26753 ;  . W  |Pl. frei: 4294967292 -1|Bäume:       1  +0|Schößlinge:    4  +0|
 12: 27302 ; - XXX (xxx), 1(+4294967153) Person
 13: 27386 ; + YYY (yyy), 52(+4294967291) Personen

**Comment by gulrak** [comment]
Leider verstehe ich mit dem Fragment noch nicht, wie es zu der Ausgabe kam, der betreffende Code ist zwar auf 32 Bit limitiert, aber wenn in der Region nicht etwa 4.3 Mrd. Bauern stehen, sollte das nicht passieren. Ich brauche etwas mehr Infos um das nachzustellen. Gerne per Mail oder Discord, wenn es Spielrelevante Infos sind.

**Comment by gulrak** [comment]
Hab eine passende Region gefunden, Bug nachgestellt und in v1.7.4 gefixt.
