### ISSUE TITLE
Bei im Bau befindlichen Flotten wird die Zielgrösse falsch angegeben

### ISSUE THREAD

**Issue by gulrak** [gulrak/pbemtools#20]
```
; An Bord von Galeone 'Foobar' (fob), Anzahl 30, im Bau (23450/2000):
```
sollte
```
; An Bord von Galeone 'Foobar' (fob), Anzahl 30, im Bau (23450/60000):
```
sein.

**Comment by Xolgrim** [comment]
Der NR gibt auch bei im Bau befindlichen Schiffen die die Zuladung an und die aktuelle Kapazität. Letztere ist natürlich im bau immer 0
Beispiel:
Galeone 1bvd (1bvd), 12 Galeonen, (60/0), im Bau (1836/24000).

    * Segler (ccc), 6 Nebelmeermenschen, kämpft nicht, <-- die 60GE

**Comment by gulrak** [comment]
Fix released mit [v1.7.6](https://gulrak.de/posts/2021-vorlage-version-v1-7-6/).
