### ISSUE TITLE
Bewachende Parteien anzeigen

### ISSUE THREAD

**Issue by Xolgrim** [gulrak/pbemtools#21]
Die Information wer eine Region bewacht ist sehr wichtig, es wäre schön wenn das auch dargestellt werden würde.

"Die Region wird von Erben Chelestras (ech) und Bàn bean si (eLfe) bewacht."

Um das Nachzubilden solltest du genug .cr Material haben, ich helf aber gerne aus, falls nötig.

**Comment by gulrak** [comment]
Ich schau mal ob ich das noch mit reinbekomme, in das kommende Release. Müsste klappen.

**Comment by gulrak** [comment]
Fix released mit [v1.7.6](https://gulrak.de/posts/2021-vorlage-version-v1-7-6/).
